CREATE TABLE associado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    nome VARCHAR(255)
);

CREATE TABLE pauta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_criacao TIMESTAMP NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    titulo VARCHAR(255) NOT NULL
);

CREATE TABLE sessao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abertura TIMESTAMP NOT NULL,
    duracao_minutos INTEGER NOT NULL,
    fechamento TIMESTAMP NOT NULL,
    pauta_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_sessao_pauta FOREIGN KEY (pauta_id) REFERENCES pauta(id)
);

CREATE TABLE voto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor BOOLEAN NOT NULL,
    id_associado BIGINT NOT NULL,
    id_sessao BIGINT NOT NULL,
    CONSTRAINT fk_voto_associado FOREIGN KEY (id_associado) REFERENCES associado(id),
    CONSTRAINT fk_voto_sessao FOREIGN KEY (id_sessao) REFERENCES sessao(id),
    CONSTRAINT unique_voto UNIQUE (id_associado, id_sessao)
);
